# Version
version: '3.1'

# Services
services:
  backend:
    container_name: milestone
    image: milestone
    restart: always
    build: ./
    ports:
      - "4444:4444"
    networks:
      - milestone_network

# Networks
networks:
  milestone_network:
    name: milestone_network
    driver: bridge

